In [127]:
from helper_loader import *
from histalign.backend.models import Orientation

In [ ]:
x_axis = vedo.Arrow(end_pt=(1, 0, 0), c="red", s=0.001)
y_axis = vedo.Arrow(end_pt=(0, 1, 0), c="yellow", s=0.001)
z_axis = vedo.Arrow(end_pt=(0, 0, 1), c="blue", s=0.001)

axes = [x_axis, y_axis, z_axis]

In [128]:
def compute_normal(
    orientation: Orientation, pitch: int = 0, yaw: int = 0
) -> np.ndarray:
    pitch = math.radians(pitch)
    yaw = math.radians(yaw)

    match orientation:
        case Orientation.CORONAL:
            pitch *= 1
            yaw *= -1
            normal = [
                -math.cos(pitch) * math.cos(yaw),
                -math.sin(pitch) * math.cos(yaw),
                -math.sin(yaw),
            ]
        case Orientation.HORIZONTAL:
            normal = [
                math.sin(pitch),
                math.cos(yaw) * math.cos(pitch),
                math.sin(yaw) * math.cos(pitch),
            ]
        case Orientation.SAGITTAL:
            normal = [
                math.sin(yaw),
                math.sin(pitch) * math.cos(yaw),
                math.cos(pitch) * math.cos(yaw),
            ]

    return np.array(normal)

In [ ]:
def compute_normal(orientation: str, pitch: int = 0, yaw: int = 0) -> np.ndarray:
    pitch = math.radians(pitch)
    yaw = math.radians(yaw)

    match orientation:
        case "coronal":
            normal = [
                math.cos(yaw) * math.cos(pitch),
                -math.sin(pitch),
                -math.sin(yaw) * math.cos(pitch),
            ]
        case "horizontal":
            normal = [
                math.sin(pitch),
                math.cos(yaw) * math.cos(pitch),
                math.sin(yaw) * math.cos(pitch),
            ]
        case "sagittal":
            normal = [
                math.sin(yaw_radians) * math.cos(pitch_radians),
                math.sin(pitch_radians),
                math.cos(yaw_radians) * math.cos(pitch_radians),
            ]

    return np.array(normal)

In [106]:
def compute_normal(orientation: str, pitch: int = 0, yaw: int = 0) -> np.ndarray:
    pitch = math.radians(pitch)
    yaw = math.radians(yaw)

    match orientation:
        case "coronal":
            normal = [
                math.cos(yaw) * math.cos(pitch),
                math.sin(yaw) * math.cos(pitch),
                math.sin(pitch),
            ]
        case "horizontal":
            normal = [
                math.sin(pitch),
                math.cos(yaw) * math.cos(pitch),
                math.sin(yaw) * math.cos(pitch),
            ]
        case "sagittal":
            normal = [
                math.sin(yaw),
                math.sin(pitch) * math.cos(yaw),
                math.cos(pitch) * math.cos(yaw),
            ]

    return np.array(normal)

In [122]:
traditional_back_of_x_camera = dict(
    position=(-5, 0, 0),
    focal_point=(0, 0, 0),
    viewup=(0, 0, 1),
)

In [ ]:
def compute_normal(
    orientation: Orientation, pitch: int = 0, yaw: int = 0
) -> np.ndarray:
    pitch = math.radians(pitch)
    yaw = math.radians(yaw)

    match orientation:
        case Orientation.CORONAL:
            yaw *= -1
            normal = [
                -math.cos(pitch) * math.cos(yaw),
                -math.sin(pitch) * math.cos(yaw),
                -math.sin(yaw),
            ]
        case Orientation.HORIZONTAL:
            normal = [
                -math.sin(pitch),
                math.cos(yaw) * math.cos(pitch),
                math.sin(yaw) * math.cos(pitch),
            ]
        case Orientation.SAGITTAL:
            normal = [
                math.sin(yaw),
                -math.sin(pitch) * math.cos(yaw),
                math.cos(pitch) * math.cos(yaw),
            ]

    return np.array(normal)

In [ ]:
def compute_normal(
    orientation: Orientation, pitch: int = 0, yaw: int = 0
) -> np.ndarray:
    pitch = math.radians(pitch)
    yaw = math.radians(yaw)

    match orientation:
        case Orientation.CORONAL:
            yaw *= -1
            normal = [
                -math.cos(pitch) * math.cos(yaw),
                -math.sin(pitch) * math.cos(yaw),
                -math.sin(yaw),
            ]
        case Orientation.HORIZONTAL:
            normal = [
                math.sin(pitch),
                math.cos(yaw) * math.cos(pitch),
                math.sin(yaw) * math.cos(pitch),
            ]
        case Orientation.SAGITTAL:
            normal = [
                math.sin(yaw),
                math.sin(pitch) * math.cos(yaw),
                math.cos(pitch) * math.cos(yaw),
            ]

    return np.array(normal)

In [ ]:
def compute_normal(orientation: Orientation, pitch: int, yaw: int) -> list[float]:
    pitch = math.radians(pitch)
    yaw = math.radians(yaw)

    match orientation:
        case Orientation.CORONAL:
            normal = [
                math.cos(yaw) * math.cos(pitch),
                -math.sin(pitch),
                -math.sin(yaw) * math.cos(pitch),
            ]
        case Orientation.HORIZONTAL:
            normal = [
                math.sin(pitch),
                math.cos(yaw) * math.cos(pitch),
                math.sin(yaw) * math.cos(pitch),
            ]
        case Orientation.SAGITTAL:
            normal = [
                math.sin(yaw) * math.cos(pitch),
                math.sin(pitch),
                math.cos(yaw) * math.cos(pitch),
            ]
        case other:
            # Should be impossible thanks to pydantic
            raise InvalidOrientationError(other)

    return normal

In [237]:
def compute_normal_yaw_first(
    orientation: Orientation, pitch: int, yaw: int
) -> list[float]:
    pitch = math.radians(pitch)
    yaw = math.radians(yaw)

    match orientation:
        case Orientation.CORONAL:
            normal = [
                -math.cos(yaw) * math.cos(pitch),
                -math.sin(pitch),
                math.sin(yaw) * math.cos(pitch),
            ]
        case Orientation.HORIZONTAL:
            normal = [
                -math.sin(pitch),
                math.cos(yaw) * math.cos(pitch),
                math.sin(yaw) * math.cos(pitch),
            ]
        case Orientation.SAGITTAL:
            normal = [
                math.sin(yaw) * math.cos(pitch),
                -math.sin(pitch),
                math.cos(yaw) * math.cos(pitch),
            ]
        case other:
            # Should be impossible thanks to pydantic
            raise InvalidOrientationError(other)

    return normal

In [238]:
def compute_normal_pitch_first(
    orientation: Orientation, pitch: int, yaw: int
) -> list[float]:
    pitch = math.radians(pitch)
    yaw = math.radians(yaw)

    match orientation:
        case Orientation.CORONAL:
            normal = [
                -math.cos(pitch) * math.cos(yaw),
                -math.sin(pitch) * math.cos(yaw),
                math.sin(yaw),
            ]
        case Orientation.HORIZONTAL:
            normal = [
                -math.sin(pitch) * math.cos(yaw),
                math.cos(pitch) * math.cos(yaw),
                math.sin(yaw),
            ]
        case Orientation.SAGITTAL:
            normal = [
                math.sin(yaw),
                -math.sin(pitch) * math.cos(yaw),
                math.cos(pitch) * math.cos(yaw),
            ]
        case other:
            # Should be impossible thanks to pydantic
            raise InvalidOrientationError(other)

    return normal

In [ ]:
def compute_normal(
    orientation: Orientation,
    pitch: int = 0,
    yaw: int = 0,
    pitch_first: bool = True,
) -> np.ndarray:
    """Computes the normal to the plane described by orientation and principal axes.

    Note that rotations are not commutative, hence the `pitch_first` argument.
    By default, pitch rotation if applied first.

    Adapted from this StackOverflow exchange: https://math.stackexchange.com/q/2618527.

    Args:
        orientation (Orientation): Orientation to determine which axis to "look out of".
                                   For example, given a coronal orientation, the
                                   normal without any rotations would be (-1, 0, 0).
        pitch (int): Angle in degree with which to raise the normal.
        yaw (int): Angle in degrees with which to rotate around the vertical axis.
        pitch_first (bool, optional): Whether to apply pitch before yaw.

    Returns:
        np.ndarray: The normal to the orientation plane after applying applying the
                    rotations.

    Examples:
        Working with a sagittal orientation, the plane that is being rotated is the one
        described by the X and Y axes. Given the way the Allen CCF is oriented, the
        normal without any rotations is (0, 0, 1), i.e., looking out of the
        medio-lateral axis, with the dorso-ventral axis pointing down and the
        rostro-caudal axis pointing right.

        Therefore, applying a pitch of 20 degrees tilts the plane
        back by 20 degrees, giving us a normal with a negative Y component and a reduced
        Z component.

        > compute_normal(Orientation.SAGITTAL, pitch=20, yaw=0)
        array([ 0.        , -0.34202014,  0.93969262])

        Similarly, a 20 degrees yaw rotates to the right, giving us a positive X
        component and a reduced Z component.

        > compute_normal(Orientation.SAGITTAL, pitch=0, yaw=20)
        array([ 0.34202014, -0.        ,  0.93969262])

        And a combination of the two gives us components for all the axes.

        > compute_normal(Orientation.SAGITTAL, pitch=20, yaw=20)
        array([ 0.34202014, -0.3213938 ,  0.88302222])

    See Also:
        https://en.wikipedia.org/wiki/Aircraft_principal_axes#Principal_axes
    """

    pitch = math.radians(pitch)
    yaw = math.radians(yaw)

    match orientation:
        case Orientation.CORONAL:
            if pitch_first:
                normal = [
                    -math.cos(pitch) * math.cos(yaw),
                    -math.sin(pitch) * math.cos(yaw),
                    math.sin(yaw),
                ]
            else:
                normal = [
                    -math.cos(yaw) * math.cos(pitch),
                    -math.sin(pitch),
                    math.sin(yaw) * math.cos(pitch),
                ]
        case Orientation.HORIZONTAL:
            if pitch_first:
                normal = [
                    -math.sin(pitch) * math.cos(yaw),
                    math.cos(pitch) * math.cos(yaw),
                    math.sin(yaw),
                ]
            else:
                normal = [
                    -math.sin(pitch),
                    math.cos(yaw) * math.cos(pitch),
                    math.sin(yaw) * math.cos(pitch),
                ]
        case Orientation.SAGITTAL:
            if pitch_first:
                normal = [
                    math.sin(yaw),
                    -math.sin(pitch) * math.cos(yaw),
                    math.cos(pitch) * math.cos(yaw),
                ]
            else:
                normal = [
                    math.sin(yaw) * math.cos(pitch),
                    -math.sin(pitch),
                    math.cos(yaw) * math.cos(pitch),
                ]
        case other:
            # Should be impossible thanks to pydantic
            raise InvalidOrientationError(other)

    return np.ndarray(normal)

In [255]:
for orientation, camera in [
    ("coronal", coronal_camera),
    ("horizontal", horizontal_camera),
    ("sagittal", sagittal_camera),
]:
    pitch = 20
    yaw = 20

    pitch_normal = compute_normal_pitch_first(orientation, pitch, 0)
    pitch_arrow = vedo.Arrow(end_pt=pitch_normal, c="cyan", s=0.002)
    pitch_plane = vedo.Plane(normal=pitch_normal, c="cyan")

    yaw_normal = compute_normal_pitch_first(orientation, 0, yaw)
    yaw_arrow = vedo.Arrow(end_pt=yaw_normal, c="magenta", s=0.002)
    yaw_plane = vedo.Plane(normal=yaw_normal, c="magenta")

    compound_normal = compute_normal_pitch_first(orientation, pitch, yaw)
    compound_arrow = vedo.Arrow(end_pt=compound_normal, c="black", s=0.002)
    compound_plane = vedo.Plane(normal=compound_normal, c="black")

    show(
        [
            pitch_plane,
            pitch_arrow,
            yaw_plane,
            yaw_arrow,
            # compound_plane,
            # compound_arrow,
            *axes,
        ],
        camera=camera,
    )

In [252]:
pitch_first_arrows = []
yaw_first_arrows = []

for i in range(0, 361, 1):
    pitch = i
    yaw = i

    pitch_first_normal = compute_normal(orientation, i, i, pitch_first=True)
    pitch_first_arrow = vedo.Arrow(end_pt=pitch_first_normal, c="white", s=0.002)
    pitch_first_arrows.append(pitch_first_arrow)

    yaw_first_normal = compute_normal(orientation, i, i, pitch_first=False)
    yaw_first_arrow = vedo.Arrow(end_pt=yaw_first_normal, c="black", s=0.002)
    yaw_first_arrows.append(yaw_first_arrow)

show(
    [
        *pitch_first_arrows,
        *yaw_first_arrows,
        *axes,
    ],
    camera=coronal_camera,
)