In [1]:
import numpy as np

from helper_loader import *

In [7]:
from math import cos, sin, radians


def compute_normal(pitch: int = 0, yaw: int = 0) -> np.ndarray:
    # Pitch = around_y clockwise = theta
    # Yaw   = around_z clockwise = phi
    yaw = radians(yaw)
    pitch = radians(pitch)

    normal = [
        cos(yaw) * cos(pitch),
        sin(yaw) * cos(pitch),
        sin(pitch),
    ]

    # y_radians = math.radians(around_z)
    # z_radians = math.radians(around_y)

    # normal = [
    #     cos(z_radians) * cos(y_radians),
    #     sin(y_radians),
    #     sin(z_radians) * cos(y_radians),
    # ]

    return np.array(normal)


pitch = 45
yaw = 45

x_axis = vedo.Arrow(end_pt=(1, 0, 0), c="red", s=0.001)
y_axis = vedo.Arrow(end_pt=(0, 1, 0), c="yellow", s=0.001)
z_axis = vedo.Arrow(end_pt=(0, 0, 1), c="blue", s=0.001)


original_normal = compute_normal(0, 0)
original_arrow = vedo.Arrow(end_pt=original_normal, c="black", s=0.002)
original_plane = vedo.Plane(normal=original_normal)

rotated_arrows = []
for i in range(0, 91, 5):
    rotated_normal = compute_normal(45, i)
    rotated_arrow = vedo.Arrow(end_pt=rotated_normal, c="white", s=0.002)
    rotated_plane = vedo.Plane(normal=rotated_normal)

    rotated_arrows.append(rotated_arrow)

equidistant_normal = np.array((1, 1, 1))
equidistant_arrow = vedo.Arrow(end_pt=equidistant_normal, c="purple", s=0.002)

rotated_normal = compute_normal(pitch, yaw)
rotated_arrow = vedo.Arrow(end_pt=rotated_normal, c="white", s=0.002)

pitch_normal = compute_normal(pitch, 0)
pitch_arrow = vedo.Arrow(end_pt=pitch_normal, c="cyan", s=0.002)

yaw_normal = compute_normal(0, yaw)
yaw_arrow = vedo.Arrow(end_pt=yaw_normal, c="magenta", s=0.002)

sum_normal = pitch_normal + yaw_normal
sum_arrow = vedo.Arrow(end_pt=sum_normal, c="pink", s=0.002)

show(
    [
        x_axis,
        y_axis,
        z_axis,
        # original_arrow,
        # original_plane,
        pitch_arrow,
        # yaw_arrow,
        # rotated_arrow,
        # equidistant_arrow,
        # sum_arrow,
        # *rotated_arrows,
    ],
    camera=sagittal_camera,
)

In [4]:
print(f"Pitch = {pitch} and yaw = {yaw}")

Pitch = 45 and yaw = 45


In [5]:
pitch_normal

array([0.70710678, 0.        , 0.70710678])

In [6]:
yaw_normal

array([0.70710678, 0.70710678, 0.        ])

In [7]:
rotated_normal

array([0.5       , 0.5       , 0.70710678])